#!/bin/sh
"/cygdrive/c/Program Files/nodejs/node" "/Documents and Settings/Beak/Application Data/npm/node_modules/jshint/bin/hint" --config=lint-config.js src/js/*.js && 
"/cygdrive/c/Program Files/nodejs/node" ../../resources/r.js -o src/build.js && \
chmod -R og+r * && \
scp out/auth.html out/index.html out/embed.html out/theme-default.css duerig@jonathonduerig.com:/var/www/blog-app.net/test &&
scp out/js/main.js out/js/embed.js duerig@jonathonduerig.com:/var/www/blog-app.net/test/js

